"""Pure analytics API for Arbiter research reports."""

from arbiter.analytics.metrics import (
    AnalyticsResult,
    AnalyticsSummary,
    Breakdown,
    BreakdownRow,
    DecimalQuantiles,
    DiagnosticFunnel,
    EpisodeFact,
    MarketContextMetricRow,
    MarketHourRate,
    MarketObservationWindowRow,
    ObservationMetricRow,
    PaperExecutionMetricRow,
    RunCohortRow,
    RunCohortSelection,
    SelectedRunCohort,
    SettlementBucket,
    build_episode_facts,
    compute_analytics,
    compute_market_hours,
    decimal_quantiles,
    market_hour_rate,
    select_run_cohorts,
    settlement_bucket,
    settlement_bucket_from_contexts,
    summarize_analytics,
)

__all__ = [
    "AnalyticsResult",
    "AnalyticsSummary",
    "Breakdown",
    "BreakdownRow",
    "DecimalQuantiles",
    "DiagnosticFunnel",
    "EpisodeFact",
    "MarketContextMetricRow",
    "MarketHourRate",
    "MarketObservationWindowRow",
    "ObservationMetricRow",
    "PaperExecutionMetricRow",
    "RunCohortRow",
    "RunCohortSelection",
    "SelectedRunCohort",
    "SettlementBucket",
    "build_episode_facts",
    "compute_analytics",
    "compute_market_hours",
    "decimal_quantiles",
    "market_hour_rate",
    "select_run_cohorts",
    "settlement_bucket",
    "settlement_bucket_from_contexts",
    "summarize_analytics",
]
